baseURL = 'https://docs.th3shadowbroker.org/'
languageCode = 'en-us'
title = 'OuroborosDocs'
theme = 'hugo-book'
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
BookTheme = 'auto'
BookMenuBundle = '/menu'
BookRepo = 'https://github.com/Th3Shadowbroker/OuroborosDocs'
BookCommitPath = 'commit'
BookEditPath = 'edit/main'
BookSection = '*'
Description = 'Text about my cool site'
Title = 'OuroborosDocs'
